schema_version = "1.0.0"
id = "node_arranger"
version = "1.0.2"
name = "Node Arranger"
tagline = "Arrange node trees with the click of a button"
maintainer = "Leonardo Pike-Excell <leonardopike.excell@gmail.com>"
type = "add-on"
website = "https://github.com/Leonardo-Pike-Excell/node-arranger"
tags = ["Node"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
